### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_super_mario_bros'

### ISSUE THREAD

**Issue by nuomizai** [sadeqa/Super-Mario-Bros-RL#3]
Hi, @otmhi @sadeqa , I've got some problem when running train-mario-curiosity.py, the error information is :
ModuleNotFoundError: No module named 'gym_super_mario_bros'. And I didn't find that file. Can you tell me where to find it? Thank you :)

**Comment by Eshwar-Anugandula** [comment]
Hi, nuomizai, I got same error, If you got to know about it do let me know
:)
